[project]
name = "personal-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-ollama>=1.0.1",
    "langchain[ollama,openai]>=1.2.6",
    "python-dotenv>=1.2.1",
    "google-auth",
    "google-auth-oauthlib",
    "google-api-python-client",
    "pyfiglet",
    "rich",
    "typer",
]
